### ISSUE TITLE
Missing map details version 3.2 dated 03.11.2017

### ISSUE THREAD

**Issue by koskinen** [pailakka/mtk2garmin#34]
Several issues with map (mtk_suomi.img, 864c92c0037184c351fdb1eb93c6da3ea0810d99) dated 03.11.2017 

Tested with Garmin Astro 320

- Farmlands not shown on map
- Houses and other buildings missing
- Map detail icons missing, e.g. vedenalainen kivi, kaisilikko and so on

**Comment by pailakka** [comment]
Could you provide a screenshot?

**Comment by koskinen** [comment]
![mtk_suomi_2c](https://user-images.githubusercontent.com/1726020/32622173-b9ce3180-c58a-11e7-9cc9-88d02fcb3858.jpg)
![position](https://user-images.githubusercontent.com/1726020/32622174-b9ffa620-c58a-11e7-84ff-be5f550b2f3d.jpg)
![mtk_suomi_32](https://user-images.githubusercontent.com/1726020/32622175-ba28cb36-c58a-11e7-84b0-25f37b219a73.jpg)

**Comment by pailakka** [comment]
Does the Astro 320 have night mode enabled?

**Comment by koskinen** [comment]
Yes, appartently the device had night mode active. The data is also missing when day-mode is active.

**Comment by pailakka** [comment]
Is this still reproducible with the latest version?
